# Site settings
title: BMX Bash
email: leigh765@me.com
description: "Bob's BBQ is proud to support the first annual BMX Bonaza."
twitter_username: bobsbbqbmx

# url: http://carbondesign.github.io/bna
url: http://localhost:4000/
# Build settings
markdown: kramdown
permalink: pretty
